name: Questions & Help
description: Ask a question
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: What do you want to ask?
      placeholder: Describe your question.
    validations:
      required: true
